# This is a basic workflow that is manually triggered

name: Zip it up

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      message:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Commit Message'
        # Default value if no value is explicitly provided
        default: 'New Build'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Git Setup
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      # Runs a set of commands using the runners shell
      - name: Zip and Ship
        run: |
          zip -r build.zip .
          git add build.zip
          git commit -m "${{ github.event.inputs.message }}"
          git push origin master
